apiVersion: v1
kind: Service
metadata:
  name: engine-core
  namespace: quant-system
  labels:
    app: engine-core
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  selector:
    app: engine-core
  ports:
    - name: http
      port: 8080
      targetPort: http
