apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - engine-core-deployment.yaml
  - engine-core-service.yaml
  - engine-core-pdb.yaml
  - strategy-runner-deployment.yaml
  - strategy-runner-service.yaml
  - strategy-runner-pdb.yaml
  - market-ingest-deployment.yaml
  - market-ingest-service.yaml
  - nats-service.yaml
  - nats-statefulset.yaml
  - nats-pdb.yaml
  - mysql-secret.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - mysql-pdb.yaml
