apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: engine-core
  namespace: quant-system
spec:
  namespaceSelector:
    matchNames:
      - quant-system
  selector:
    matchLabels:
      app: engine-core
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 3s
